export enum EstadoId {
    ASIGNADO = 1,
    ARMADO_CARTAS = 2,
    REVISION_SENIOR = 3,
    PODER_EQUIPO_AUDITORIA = 4,
    PROCESO_ENVIO = 5,
    ENVIADO = 6,
    FINALIZADO = 7,
    CONSULTA_EQUIPO_AUDITORIA = 8,
    CANCELADO = 9,
    ENVIO_CONFIRMATION = 10
}